project:
  type: website
  output-dir: docs
  
  resources:
    - images

website:
  navbar:
    title: "Snapshot Paraguay"
    left: []
    right:
      - text: "Inicio"
        href: "#inicio"
      - text: "Sobre el proyecto"
        href: "#sobre-proyecto"
      - text: "Protocolo e inscripción"
        href: "#protocolo"
      - text: "Galería"
        href: "#galeria"
      - text: "Contacto"
        href: "#contacto"

format:
  html:
    theme: cosmo
    css: styles.css
    smooth-scroll: true
    include-in-header: lightbox.html
    

lang: es
